import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { DesktopHeader } from "@/components/website-layout/desktop/DesktopHeader";
import DesktopFooter from "@/components/website-layout/desktop/DesktopFooter";

const inter = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  antialiased bg-black text-white`}>
        <DesktopHeader />
        {children}
        <DesktopFooter />
      </body>
    </html>
  );
}
